---
- hosts: localhost
  become: true
  gather_facts: true
  connection: local
  roles:

    - role: redhatofficial.rhel8_stig
      vars:
        high_severity: true
        medium_severity: true
        low_severity: false
        unknown_severity: false
        enable_fips_mode: true
        sudo_remove_nopasswd: false
        sysctl_user_max_user_namespaces: false
        service_fapolicyd_enabled: false
        mount_option_nodev_nonroot_local_partitions: false
        mount_option_dev_shm_nodev: false
        mount_option_dev_shm_noexec: false
        mount_option_dev_shm_nosuid: false
        accounts_minimum_age_login_defs: false
        accounts_maximum_age_login_defs: false
        accounts_password_minlen_login_defs: false
        require_emergency_target_auth: false
        require_singleuser_auth: false
        accounts_logon_fail_delay: false
        sshd_disable_root_login: false

  tasks:

      # Create file to indicate hardening has been completed
    - name: Touch file to indicate hardening has been done
      ansible.builtin.file:
        path: /etc/sysconfig/rh-quay-hardened
        state: touch
        mode: u=rw,g=r,o=r
